
/* Redux action names */

export const REQUEST_WEIGHTS = 'REQUEST_WEIGHTS'
export const RECEIVE_WEIGHTS = 'RECEIVE_WEIGHTS'

export const RECEIVE_SAVE_WEIGHT = 'RECEIVE_SAVE_WEIGHT'
export const RECEIVE_CLEAR_WEIGHT = 'RECEIVE_CLEAR_WEIGHT'

export const RECEIVE_NOTES = 'RECEIVE_NOTES'
export const RECEIVE_ADD_NOTE = 'RECEIVE_ADD_NOTE'
export const RECEIVE_DELETE_NOTE = 'RECEIVE_DELETE_NOTE'

export const SET_WEIGHT_DAY_LIMIT = 'SET_WEIGHT_DAY_LIMIT'
