name: CI

on: 
  push:
    tags: 
      - rel/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build docker image
      run: |
        docker login --username "${DOCKER_LOGIN}" --password "${DOCKER_PASS}"
        docker build . -t nurpax/hswtrack2:latest
        docker push nurpax/hswtrack2:latest
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
